adb:
  active_profile: MuMu 本机
  path: D:/Program Files/Netease/MuMu/nx_device/12.0/shell/adb.exe
  profiles:
  - device_serial: null
    emulator: mumu
    host: 127.0.0.1
    name: MuMu 本机
    port: 16416
app:
  name: 金铲铲智能助手
  version: 0.1.0
automation:
  auto_buy: true
  auto_draft: false
  auto_equip: false
  auto_level_up: false
  auto_position: false
  auto_refresh: false
  mode: semi_auto
debug:
  enabled: true
emulator:
  height: 720
  width: 1280
recognizer:
  debug: true
  use_gpu: true
screenshot:
  interval_ms: 1000
  region: null
season:
  current: s18_mode4
ui:
  scale: 1.0
  theme: dark
